export * from "./listsActions";
export * from "./cardsActions";
export * from "./classActions";

export const CONSTANTS = {
  ADD_CARD: "ADD_CARD",
  ADD_LIST: "ADD_LIST",
  DRAG_HAPPENED: "DRAG_HAPPENED",
  EDIT_CARD_TITLE: "EDIT_CARD_TITLE",
  EDIT_CARD_DATE: "EDIT_CARD_DATE",
  DELETE_CARD: "DELETE_CARD",
  EDIT_LIST_TITLE: "EDIT_LIST_TITLE",
  DELETE_LIST: "DELETE_LIST",
  SET_ACTIVE_CLASS: "SET_ACTIVE_CLASS",
  ADD_CLASS: "ADD_CLASS",
  DELETE_CLASS: "DELETE_CLASS",
  EDIT_CLASS_TITLE: "EDIT_CLASS_TITLE",
  ADD_LIST_BY_ID: "ADD_LIST_BY_ID",
  ADD_CLASS_WITH_LISTS: "ADD_CLASS_WITH_LISTS",
  SET_LIST: "SET_LIST",
};
